import type { FiiData } from '../../types'

interface RawFiiInput {
  ticker: string
  book_value_per_share: number
  pvp: number
  dividend_yield_ttm: number
  net_asset_value: number
  shares_outstanding: number
  segment: string
  fund_type: string
  property_count: number
  total_area_sqm: number
  vacancy_pct: number
}

function buildFii(raw: RawFiiInput): FiiData {
  const close_price = Math.round(raw.pvp * raw.book_value_per_share * 100) / 100

  return {
    ticker: raw.ticker,
    name: `${raw.ticker} - Fundo Imobiliario`,
    reference_date: '2026-07-22',
    close_price,
    book_value_per_share: raw.book_value_per_share,
    pvp: raw.pvp,
    dividend_yield_ttm: raw.dividend_yield_ttm,
    net_asset_value: raw.net_asset_value,
    shares_outstanding: raw.shares_outstanding,
    total_shareholders: Math.floor(raw.shares_outstanding * 0.015),
    segment: raw.segment,
    management_type: 'Gestao Ativa',
    administrator: 'Administradora Padrao S.A.',
    administrator_cnpj: '00000000000191',
    mandate: 'Renda',
    inception_date: '2015-01-01',
    duration_type: 'Indeterminado',
    target_investors: 'INVESTIDORES EM GERAL',
    website: `www.${raw.ticker.toLowerCase()}.com.br`,
    email: `ri@${raw.ticker.toLowerCase()}.com.br`,
    fund_type: raw.fund_type,
    property_count: raw.property_count,
    total_area_sqm: raw.total_area_sqm,
    vacancy_pct: raw.vacancy_pct,
    delinquency_pct: 0,
    leased_pct: 100 - raw.vacancy_pct,
    top_properties: [],
    property_reference_date: '2026-06-30',
  }
}

const rawFiis: RawFiiInput[] = [
  {
    ticker: 'HGLG11',
    book_value_per_share: 148.32,
    pvp: 1.10,
    dividend_yield_ttm: 8.74,
    net_asset_value: 4_523_000_000,
    shares_outstanding: 30_498_200,
    segment: 'Logistica',
    fund_type: 'Tijolo',
    property_count: 28,
    total_area_sqm: 1_595_382.91,
    vacancy_pct: 2.91,
  },
  {
    ticker: 'KNRI11',
    book_value_per_share: 135.40,
    pvp: 1.05,
    dividend_yield_ttm: 9.12,
    net_asset_value: 3_890_000_000,
    shares_outstanding: 28_720_000,
    segment: 'Hibrido',
    fund_type: 'Hibrido',
    property_count: 35,
    total_area_sqm: 1_200_000,
    vacancy_pct: 3.5,
  },
  {
    ticker: 'MXRF11',
    book_value_per_share: 9.80,
    pvp: 1.02,
    dividend_yield_ttm: 13.50,
    net_asset_value: 2_100_000_000,
    shares_outstanding: 214_000_000,
    segment: 'Papel',
    fund_type: 'Papel',
    property_count: 0,
    total_area_sqm: 0,
    vacancy_pct: 0,
  },
  {
    ticker: 'XPLG11',
    book_value_per_share: 95.20,
    pvp: 1.08,
    dividend_yield_ttm: 9.30,
    net_asset_value: 3_200_000_000,
    shares_outstanding: 33_600_000,
    segment: 'Logistica',
    fund_type: 'Tijolo',
    property_count: 22,
    total_area_sqm: 1_100_000,
    vacancy_pct: 4.2,
  },
  {
    ticker: 'KNIP11',
    book_value_per_share: 98.50,
    pvp: 0.95,
    dividend_yield_ttm: 10.20,
    net_asset_value: 2_800_000_000,
    shares_outstanding: 28_400_000,
    segment: 'Papel',
    fund_type: 'Papel',
    property_count: 0,
    total_area_sqm: 0,
    vacancy_pct: 0,
  },
  {
    ticker: 'BCFF11',
    book_value_per_share: 52.30,
    pvp: 0.98,
    dividend_yield_ttm: 11.80,
    net_asset_value: 1_900_000_000,
    shares_outstanding: 36_300_000,
    segment: 'Papel',
    fund_type: 'Papel',
    property_count: 0,
    total_area_sqm: 0,
    vacancy_pct: 0,
  },
  {
    ticker: 'KNHY11',
    book_value_per_share: 105.80,
    pvp: 0.92,
    dividend_yield_ttm: 12.40,
    net_asset_value: 1_500_000_000,
    shares_outstanding: 14_200_000,
    segment: 'Hibrido',
    fund_type: 'Hibrido',
    property_count: 10,
    total_area_sqm: 450_000,
    vacancy_pct: 1.8,
  },
  {
    ticker: 'VISC11',
    book_value_per_share: 115.60,
    pvp: 1.03,
    dividend_yield_ttm: 9.50,
    net_asset_value: 2_600_000_000,
    shares_outstanding: 22_500_000,
    segment: 'Logistica',
    fund_type: 'Tijolo',
    property_count: 18,
    total_area_sqm: 890_000,
    vacancy_pct: 2.3,
  },
  {
    ticker: 'HSML11',
    book_value_per_share: 88.40,
    pvp: 0.97,
    dividend_yield_ttm: 10.80,
    net_asset_value: 1_800_000_000,
    shares_outstanding: 20_400_000,
    segment: 'Shopping',
    fund_type: 'Tijolo',
    property_count: 12,
    total_area_sqm: 320_000,
    vacancy_pct: 5.1,
  },
  {
    ticker: 'XPML11',
    book_value_per_share: 110.20,
    pvp: 1.06,
    dividend_yield_ttm: 8.90,
    net_asset_value: 3_100_000_000,
    shares_outstanding: 28_100_000,
    segment: 'Shopping',
    fund_type: 'Tijolo',
    property_count: 15,
    total_area_sqm: 480_000,
    vacancy_pct: 4.5,
  },
  {
    ticker: 'HFOF11',
    book_value_per_share: 72.80,
    pvp: 0.88,
    dividend_yield_ttm: 11.20,
    net_asset_value: 1_200_000_000,
    shares_outstanding: 16_500_000,
    segment: 'FoF',
    fund_type: 'FoF',
    property_count: 0,
    total_area_sqm: 0,
    vacancy_pct: 0,
  },
  {
    ticker: 'RBRR11',
    book_value_per_share: 78.50,
    pvp: 0.94,
    dividend_yield_ttm: 10.50,
    net_asset_value: 1_600_000_000,
    shares_outstanding: 20_400_000,
    segment: 'Papel',
    fund_type: 'Papel',
    property_count: 0,
    total_area_sqm: 0,
    vacancy_pct: 0,
  },
  {
    ticker: 'GARE11',
    book_value_per_share: 65.20,
    pvp: 1.12,
    dividend_yield_ttm: 7.80,
    net_asset_value: 950_000_000,
    shares_outstanding: 14_600_000,
    segment: 'Lajes Corporativas',
    fund_type: 'Tijolo',
    property_count: 8,
    total_area_sqm: 210_000,
    vacancy_pct: 8.3,
  },
  {
    ticker: 'VINO11',
    book_value_per_share: 55.90,
    pvp: 0.85,
    dividend_yield_ttm: 12.10,
    net_asset_value: 1_100_000_000,
    shares_outstanding: 19_700_000,
    segment: 'Lajes Corporativas',
    fund_type: 'Tijolo',
    property_count: 6,
    total_area_sqm: 150_000,
    vacancy_pct: 12.5,
  },
]

export const mockFiis: FiiData[] = rawFiis.map(buildFii)

export function buildMockFii(overrides?: Partial<RawFiiInput>): FiiData {
  const base: RawFiiInput = {
    ticker: 'TEST11',
    book_value_per_share: 100,
    pvp: 1.0,
    dividend_yield_ttm: 9.0,
    net_asset_value: 1_000_000_000,
    shares_outstanding: 10_000_000,
    segment: 'Hibrido',
    fund_type: 'Hibrido',
    property_count: 5,
    total_area_sqm: 100_000,
    vacancy_pct: 3.0,
    ...overrides,
  }
  return buildFii(base)
}
